### ISSUE TITLE
Question: Browser component and cache

### ISSUE THREAD

**Issue by etotopuc** [HorlogeSkynet/thunderbird-user.js#14]
First of all, thanks for the effort to provide a user.js for Thunderbird.

The objective mentions that the browser components are disabled as much as possible. And while I can understand that a separation from the browser should be achieved here, I wonder what Thunderbird actually uses the browser functions for. Apart from calling the addon management, links are passed directly to the external browser, aren't they?

And the second question: What does Thunderbird use the `browser.cache.x` settings for? That doesn't pertain to caching or keeping emails ready, does it?

**Comment by HorlogeSkynet** [comment]
> First of all, thanks for the effort to provide a user.js for Thunderbird.

Hey ! Thanks, appreciated 🙇

> The objective mentions that the browser components are disabled as much as possible. And while I can understand that a separation from the browser should be achieved here, I wonder what Thunderbird actually uses the browser functions for. Apart from calling the addon management, links are passed directly to the external browser, aren't they?

Indeed, I _guess_ they had not been widely disabled in the past in order to keep the add-ons Web part fully-functional. On the links handling, I fear a regular "YMMV" would be answer here, as it might differ across operating systems and/or due to system settings. Also, but I'm not an expert about Mozilla's code bases, `browser.*` settings _might_ affect more things than you and I may expect (everything is about "Web" now...).

> And the second question: What does Thunderbird use the `browser.cache.x` settings for? That doesn't pertain to caching or keeping emails ready, does it?

I do not know the specifics about this, but I _think_ they only concern _regular_ Web-browsing when performed within a **Web** tab. Unlike Arkenfox (where it might be a good idea to leave it enabled), I've decided to explicitly keep this "feature" (more of a "behavior" actually) disabled. About your question, I haven't experienced any email caching issues across my personal setups, so I guess they are completely unrelated (but I haven't managed to find a "global" preference for this kind of caching).

Bye 👋

**Comment by HorlogeSkynet** [comment]
Closing here, feel free to experiment and propose some changes to the _template_ if you think/work out we are currently too "permissive" for emailing-only usages. 👋

**Comment by HorlogeSkynet** [comment]
FYI, while investigating #26, we noticed that "browser" cache feature is actually being used to download email attachments in RAM (when they are not available in account folder, on disk).
