### ISSUE TITLE
[BUG] [deleted]

### ISSUE THREAD

**Issue by 34candos** [HorlogeSkynet/thunderbird-user.js#29]
[deleted]

**Comment by 34candos** [comment]
PS: serves me right for now pasting overrides at the end of user.js. An updater script would come in handy.

**Comment by HorlogeSkynet** [comment]
Hi @34candos,

1. Could you revert your OP/title deletion ? Due to #28, it's true that previous "remote content" exceptions could disappear (I guess FPI is to blame here), it may help others.

2. Yes, see [here](https://github.com/HorlogeSkynet/thunderbird-user.js/projects/1#card-84176010).
  At the moment, I still haven't decided whether I can/want to maintain "upstream" scripts here. Focusing on the template is already pretty time-consuming, and any help appreciated :bow:

Thanks, bye :wave:

**Comment by 34candos** [comment]
Previously set exceptions did reappear in the list after adding the overrides. So they hadn't really been deleted, they were just not loaded or something.

**Comment by HorlogeSkynet** [comment]
Does your override deal with FPI, persistent storage or sanitation on shutdown ?
Maybe related to #23 and `permissions.memory_only` ?

:wave:

**Comment by 34candos** [comment]
I think so, yes. At any rate, it's fixed and I should have remembered to copy overrides :)
