### ISSUE TITLE
new pref suggestions

### ISSUE THREAD

**Issue by atomGit** [HorlogeSkynet/thunderbird-user.js#3]
re: t-bird v68

```javascript
user_pref("beacon.enabled", false);  // whether to send additional analytics to web servers
user_pref("canvas.capturestream.enabled", false);  // whether to allow Canvas video capture
user_pref("dom.storage.enabled", false); //  whether to enable DOM storage
user_pref("general.useragent.compatMode.firefox", true);  // whether to limit sending extra user-agent data
user_pref("mail.cloud_files.enabled", false); // whether to enable cloud storage functionality - for storing large attachments in the cloud apparently
user_pref("messenger.startup.action", 0); // whether to enable chat on startup
user_pref("pref.privacy.disable_button.view_cookies", false);  // whether to disable the 'Show Cookies' button
user_pref("security.mixed_content.block_object_subrequest", true); // whether to block unencrypted requests from Flash on encrypted pages
user_pref("security.warn_entering_weak", true); // whether to warn when a website uses weak security
user_pref("security.warn_viewing_mixed", true); // whether to warn when a website contains both secure and insecure content

**Comment by HorlogeSkynet** [comment]
I'm preparing a commit for these changes, thank you again.

Some feedbacks though :

* `canvas.capturestream.enabled` : Looks deprecated since v67 by checking at gHacks (https://github.com/ghacksuserjs/ghacks-user.js/commit/8b07fd57d0f8a31dab25661d51235fe1b0c6360c)
* `dom.storage.enabled` : I'd add it to the template, but commented as for Firefox (https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js#L1248). Are you OK with this ?
* `pref.privacy.disable_button.view_cookies` : On my machine, I can notice also `pref.privacy.disable_button.{cookie_exceptions,view_passwords}` modified (and thus disabled) but I don't know who/what did this 🤔. Do you think we should include them as well ?

See you on #4, closing here !

**Comment by atomGit** [comment]
`canvas.capturestream.enabled` - could be depreciated, i dunno - i checked only in TB's config editor and it's still there (def=true)

> `dom.storage.enabled` :  I'd add it to the template, but commented as for Firefox. Are you OK with this ?

sure
i'm not sure where you want to go with the template - personally i use TB only for mail (no browsing, chat, etc.) and in this case i think it's better to disable DOM storage - with FF it's a totally different story obviously

> `pref.privacy.disable_button.view_cookies` : On my machine, I can notice also `pref.privacy.disable_button`.{cookie_exceptions,view_passwords} modified (and thus disabled) but I don't know who/what did this thinking. Do you think we should include them as well ?

i don't know - these prefs aren't really related to security or privacy (and i didn't really think of this when i suggested it) so i don't know what to say  - i'm not seeing any `view_passwords` on my box (Linux) - maybe cause i haven't stored any in TB

this brings up a question ... what do you want to focus on with the .js?

if it's only privacy and security, several of the existing prefs could be dropped and hopefully this would result in less work for you ???

i don't really have a preference, but if you want to go that route, let me know and i'll be happy to compile a list of prefs that can be removed if you like

**Comment by HorlogeSkynet** [comment]
> `canvas.capturestream.enabled` - could be depreciated, i dunno - i checked only in TB's config editor and it's still there (def=true)

I guess it has been removed from gHacks as RFP [is supposed to **mitigate** those _leaks_](https://github.com/kkapsner/CanvasBlocker/issues/349) (thus "deprecated" from a gHacks point of view, but not from FF/TB ones, as it is still enabled by default on both latest releases).
I'll add it to section `4600`, as an optional alternative to RFP.

> [...] in this case i think it's better to disable DOM storage - with FF it's a totally different story obviously

You are absolutely right, I just feared it would break Add-Ons page for instance, but it should not.
I'll make it disabled by default on #4.

> i don't know - these prefs aren't really related to security or privacy (and i didn't really think of this when i suggested it) so i don't know what to say - i'm not seeing any view_passwords on my box (Linux) - maybe cause i haven't stored any in TB

Well, I'm not very keen about softwares _hiding_ anything from users, so let's disable these options too.

> i'm not sure where you want to go with the template - personally i use TB only for mail (no browsing, chat, etc.) [...]
> this brings up a question ... what do you want to focus on with the .js?
> if it's only privacy and security, several of the existing prefs could be dropped and hopefully this would result in less work for you ???
> i don't really have a preference, but if you want to go that route, let me know and i'll be happy to compile a list of prefs that can be removed if you like

Well I don't have a specific roadmap but your comment made me think a bit about that.
I think we should keep the template as exhaustive as possible (and clear), in order to let users compile their own version (`"Power to the users !"` has just yelled someone at the back).
Sooo, let's keep track of upstream changes, and compile there a proper list honoring the project description 😏

&rarr; Be ready for a #4 review 🙇

**Comment by atomGit** [comment]
re: `dom.storage.enabled`

> What do you think about TB extensions requiring it ?

i don't know how this works - i have a few exts. installed that store settings and disabling this doesn't affect them

do any exts. rely on it? i don't know

i don't think (not sure) DOM storage is where ext. developers are supposed to be storing settings - i've also seen fallback code in an extension where if the suggested method of storage is disabled, another is used (uBlock perhaps) - i don't know if that's suggested as a template for all developers or not

**Comment by atomGit** [comment]
to add to that... if you clear all cache in Firefox, i think that clears DOM storage also, but this has no effect on extensions - that stuff is supposed to be kept separate from web cache

**Comment by HorlogeSkynet** [comment]
Well, feel free to open a PR, I'll be glad to draft a v68-beta3 😉
