### ISSUE TITLE
[RFC] Remove some unnessecary configs

### ISSUE THREAD

**Issue by trytomakeyouprivate** [HorlogeSkynet/thunderbird-user.js#35]
**Is your feature request related to a problem? Please describe.**
There are some settings that are just plain unnessecary, I havent gone through all, but having them with a user.js means they are forced and cant be changed.

**List the concerned preferences**
```js
user_pref("mail.SpellCheckBeforeSend", true); //should be optional
user_pref("mail.html_compose", false); //can be changed in GUI, its just a "no HTML killswitch" for paranoid people
user_pref("mail.default_send_format", 0); //defaults to plain text, only changes if you use formatting, best experience
user_pref("mail.inline_attachments", true); //where is the problem? In sanitized HTML no images are really shown anyways
```
**Describe alternatives you've considered**
changing these settings manually with sed

**Checklist**

- [x] I know `thunderbird user.js` is a **template** and personal preferences should be stored elsewhere ;
- [x] The change I want to propose should globally improve the `usability / ( privacy + security + anti-fingerprinting )` ratio ;
- [x] I agree that subsequent modifications to my change scope may occur in the future.

**Comment by trytomakeyouprivate** [comment]
great work by the way! I will use it and automate my modifications

**Comment by HorlogeSkynet** [comment]
Hello @trytomakeyouprivate,

> but having them with a user.js means they are forced and cant be changed.

This project uses `user_pref` directives (not `locked`), this means that they **can** be changed (either manually from `about:config` at runtime, automatically using a TB add-on, and mainly from another `user_pref` at the end of your `user.js`.

My two cents below about your removals proposal :

* `mail.SpellCheckBeforeSend` has not been touched since initial release : I'm okay for a "reset" ;
* about `mail.html_compose` & `mail.default_send_format`, we already discussed this in #34 ;
* `mail.inline_attachments` is disabled to force TB to show "inline" attachments as simple (external) ones, including the ones that can be "rendered" (based on MIME `Content-Disposition`).
  Even if, as you pointed out, images are out of the equation here as we sanitize HTML with `mailnews.display.html_as`, I'd rather let "inlining" globally disabled.
  However, during my source code wanderings, I also encountered [`mail.inline_attachments.text`](https://searchfox.org/comm-esr102/source/mailnews/mailnews.js#14-18) that we may add to the template (left to default though).

I would like to remind you that this project is a **template** that you should adapt according to your needs. From a "code" point of view, it can be forked and maintained as a personal GitHub project (where you would "merge" new upstream changes), or simply locally cloned with manual overrides.

> great work by the way! I will use it and automate my modifications

Thanks 🙇
If you happen to tweak Arkenfox upstream scripts (as partially proposed in arkenfox/user.js#910), please open a PR _here_ (also see related #1 and #10) !

---

A dead-simple "script" (which does not handle preferences "reset" in `prefs.js`) could be :

```bash
cat template-user.js user-override.js > user.js
```

**Comment by HorlogeSkynet** [comment]
Closing here as above proposals have been added, bye 👋
